# Generated by Django 5.0.1 on 2024-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_key_file',
            field=models.TextField(),
        ),
    ]
