# Generated by Django 5.0.1 on 2024-01-31 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_status', models.CharField(default='no', max_length=4)),
                ('shipment_id', models.JSONField(default=dict)),
                ('tracking_code', models.JSONField(default=dict)),
                ('from_address', models.JSONField(default=dict)),
                ('to_address', models.JSONField(default=dict)),
                ('parcel', models.JSONField(default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
