# Generated by Django 5.0.1 on 2024-01-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_handle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='encryption_status',
            field=models.CharField(default='no', max_length=4),
        ),
    ]
