# Generated by Django 5.0.1 on 2024-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_handle', '0002_shipment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='status',
            new_name='main_status',
        ),
        migrations.AddField(
            model_name='shipment',
            name='sub_status',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
