# Generated by Django 5.0.1 on 2024-02-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_handle', '0003_rename_status_shipment_main_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(default='', max_length=255, null=True)),
                ('rate_id', models.CharField(default='', max_length=255, null=True)),
                ('tracking_code', models.CharField(default='', max_length=255)),
                ('transaction_id', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
