# Generated by Django 5.0.1 on 2024-02-28 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_handle', '0005_payment_handle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precessing_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
    ]
